MvcApplication1/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class SessionController : Controller
    {
        private WDD2425Entities db = new WDD2425Entities();

        //
        // GET: /Session/

        public ActionResult Index()
        {
            var sessions = db.Sessions.Include("Timeslots");
            return View(sessions.ToList());
        }

        //
        // GET: /Session/Details/5

        public ActionResult Details(int id = 0)
        {
            Sessions sessions = db.Sessions.Single(s => s.Id == id);
            if (sessions == null)
            {
                return HttpNotFound();
            }
            return View(sessions);
        }

        //
        // GET: /Session/Create

        public ActionResult Create()
        {
            ViewBag.Timeslot_Id = new SelectList(db.Timeslots, "Id", "Name");
            return View();
        }

        //
        // POST: /Session/Create

        [HttpPost]
        public ActionResult Create(Sessions sessions)
        {
            if (ModelState.IsValid)
            {
                db.Sessions.AddObject(sessions);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Timeslot_Id = new SelectList(db.Timeslots, "Id", "Name", sessions.Timeslot_Id);
            return View(sessions);
        }

        //
        // GET: /Session/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Sessions sessions = db.Sessions.Single(s => s.Id == id);
            if (sessions == null)
            {
                return HttpNotFound();
            }
            ViewBag.Timeslot_Id = new SelectList(db.Timeslots, "Id", "Name", sessions.Timeslot_Id);
            return View(sessions);
        }

        //
        // POST: /Session/Edit/5

        [HttpPost]
        public ActionResult Edit(Sessions sessions)
        {
            if (ModelState.IsValid)
            {
                db.Sessions.Attach(sessions);
                db.ObjectStateManager.ChangeObjectState(sessions, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Timeslot_Id = new SelectList(db.Timeslots, "Id", "Name", sessions.Timeslot_Id);
            return View(sessions);
        }

        //
        // GET: /Session/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Sessions sessions = db.Sessions.Single(s => s.Id == id);
            if (sessions == null)
            {
                return HttpNotFound();
            }
            return View(sessions);
        }

        //
        // POST: /Session/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Sessions sessions = db.Sessions.Single(s => s.Id == id);
            db.Sessions.DeleteObject(sessions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Views/Session/Create.cshtml
@model MvcApplication1.Models.Sessions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sessions</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Code)
            @Html.ValidationMessageFor(model => model.Code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Room)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Room)
            @Html.ValidationMessageFor(model => model.Room)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hash)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hash)
            @Html.ValidationMessageFor(model => model.Hash)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Timeslot_Id, "Timeslots")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Timeslot_Id", String.Empty)
            @Html.ValidationMessageFor(model => model.Timeslot_Id)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcApplication1/Views/Session/Delete.cshtml
@model MvcApplication1.Models.Sessions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Sessions</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Room)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Room)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hash)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hash)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Timeslots.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Timeslots.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication1/Views/Session/Details.cshtml
@model MvcApplication1.Models.Sessions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Sessions</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Code)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Code)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Room)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Room)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hash)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hash)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Timeslots.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Timeslots.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication1/Views/Session/Edit.cshtml
@model MvcApplication1.Models.Sessions

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sessions</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Code)
            @Html.ValidationMessageFor(model => model.Code)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Room)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Room)
            @Html.ValidationMessageFor(model => model.Room)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hash)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hash)
            @Html.ValidationMessageFor(model => model.Hash)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Timeslot_Id, "Timeslots")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Timeslot_Id", String.Empty)
            @Html.ValidationMessageFor(model => model.Timeslot_Id)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcApplication1/Views/Session/Index.Mobile.cshtml
@model IEnumerable<MvcApplication1.Models.Sessions>

@{
    ViewBag.Title = "セッション一覧";
}

<h2>@ViewBag.Title</h2>

<div>
    <ul data-role="listview" data-theme="c" data-filter="true" data-filter-placeholder="検索">
    @foreach (var item in Model) {
        <li>
            <a href="@Url.Action("Details", new { item.Id })">
                <h4>@Html.DisplayFor(modelItem => item.Title)</h4>
                <p>Session Code: @Html.DisplayFor(modelItem => item.Code)</p>
                <p>Room: @Html.DisplayFor(modelItem => item.Room)</p>
            </a>
         </li>
    }
    </ul>
</div>

<p>
    <a href="@Url.Action("Create", "Session")" data-role="button" data-icon="plus">追加</a>
</p>

MvcApplication1/Views/Session/Index.cshtml
@model IEnumerable<MvcApplication1.Models.Sessions>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Room)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hash)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Timeslots.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Room)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hash)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Timeslots.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>